name: Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Haskell
      uses: actions/setup-haskell@v1
      with:
        ghc-version: 8.10.3  # ou une version supportée
        cabal-version: 3.4.0.0
        stack-version: latest
        
    - name: Upgrade ghcup
      run: ghcup upgrade

    - name: Install GHC with ghcup
      run: ghcup install ghc 8.10.4

    - name: Create directory for artifacts
      run: mkdir -p artifacts

    - name: Zip artifacts
      run: zip -r artifacts.zip artifacts/

    - name: List files in the working directory
      run: ls -R
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifacts
        path: ./artifacts.zip
