name: github_actions_Glados

on: push

jobs:
  test:
    name: test_the_code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # ... (d'autres étapes peuvent être ajoutées ici si nécessaire)

      - name: Notify on Discord
        if: always()  # Cette étape s'exécute toujours, même en cas d'échec précédent
        uses: Ilshidur/action-discord@v1
        with:
          args: success
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
